export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
//posts
export const REQUEST_USER_POSTS = 'REQUEST_USER_POSTS'
export const RECEIVE_USER_POSTS = 'RECEIVE_POSTS'
