export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
//posts
export const REQUEST_USER_POSTS = 'REQUEST_USER_POSTS';
export const RECEIVE_USER_POSTS = 'RECEIVE_POSTS';
export const ERROR_WRITING_POST = 'ERROR_WRITING_POST';
export const START_WRITE_POST = 'START_WRITE_POST';
export const FINISHED_WRITE_POST = 'FINISHED_WRITE_POST';
